# Generated by Django 4.2.30 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='关键词')),
                ('negative_words', models.TextField(blank=True, default='', verbose_name='否定词（逗号分隔）')),
                ('hot_score', models.IntegerField(default=0, verbose_name='热度')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'db_table': 'kw_keyword',
                'ordering': ('-hot_score', '-id'),
            },
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分组名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关键词分组',
                'verbose_name_plural': '关键词分组',
                'db_table': 'kw_group',
            },
        ),
    ]
