# Generated by Django 4.2.30 on 2026-07-31 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keywords', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_id', models.IntegerField(verbose_name='行业ID')),
                ('industry_name', models.CharField(max_length=64, verbose_name='行业名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_industries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推广员关注行业',
                'verbose_name_plural': '推广员关注行业',
                'db_table': 'promoter_industries',
                'unique_together': {('user', 'industry_id')},
            },
        ),
    ]
