# Generated by Django 4.2.30 on 2026-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='特权到期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='特权说明'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='开发者特权'),
        ),
    ]
