# Generated by Django 4.2.30 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=32, verbose_name='任务ID')),
                ('platform', models.CharField(blank=True, default='', max_length=24, verbose_name='平台')),
                ('keyword', models.CharField(blank=True, default='', max_length=128, verbose_name='关键词')),
                ('status', models.CharField(default='ok', max_length=16, verbose_name='状态')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '采集日志',
                'verbose_name_plural': '采集日志',
                'db_table': 'log_crawl',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='操作')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'log_operation',
                'ordering': ('-id',),
            },
        ),
    ]
