# Generated by Django 4.2.30 on 2026-08-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('credit_code', models.CharField(blank=True, default='', max_length=18, verbose_name='统一社会信用代码')),
                ('legal_person', models.CharField(blank=True, default='', max_length=64, verbose_name='法定代表人')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='注册资本(万)')),
                ('status', models.CharField(choices=[('active', '在业'), ('deregistered', '注销'), ('revoked', '吊销')], default='active', max_length=16, verbose_name='经营状态')),
                ('province', models.CharField(blank=True, default='', max_length=32, verbose_name='省')),
                ('city', models.CharField(blank=True, default='', max_length=32, verbose_name='市')),
                ('district', models.CharField(blank=True, default='', max_length=32, verbose_name='区县')),
                ('industry_l3', models.CharField(blank=True, default='', max_length=64, verbose_name='三级行业')),
                ('product_tags', models.JSONField(blank=True, default=list, verbose_name='业务标签')),
                ('channel_type', models.CharField(choices=[('factory', '工厂'), ('shop', '网店'), ('dealer', '经销商')], default='factory', max_length=16, verbose_name='渠道类型')),
                ('insured_count', models.IntegerField(default=0, verbose_name='参保人数')),
                ('recruit_cnt_30d', models.IntegerField(default=0, verbose_name='近30天招聘数')),
                ('tender_cnt_90d', models.IntegerField(default=0, verbose_name='近90天招标数')),
                ('patent_cnt', models.IntegerField(default=0, verbose_name='专利数')),
                ('last_tender_date', models.DateField(blank=True, null=True, verbose_name='最近招标日')),
                ('last_recruit_date', models.DateField(blank=True, null=True, verbose_name='最近招聘日')),
                ('last_financing_date', models.DateField(blank=True, null=True, verbose_name='最近融资日')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('intent_score', models.IntegerField(default=0, verbose_name='意向分')),
                ('data_version', models.IntegerField(default=1, verbose_name='数据版本')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标记')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
                'db_table': 'dim_company',
                'ordering': ('-intent_score', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ScreenTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模板名')),
                ('industry', models.CharField(blank=True, default='', max_length=64, verbose_name='行业')),
                ('conditions', models.JSONField(default=dict, verbose_name='条件快照')),
                ('is_public', models.BooleanField(default=False, verbose_name='公共模板')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '筛选模板',
                'verbose_name_plural': '筛选模板',
                'db_table': 'screen_template',
                'ordering': ('-usage_count', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=11, verbose_name='手机号(脱敏)')),
                ('phone_md5', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号MD5')),
                ('role_title', models.CharField(blank=True, default='', max_length=64, verbose_name='职位')),
                ('role_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='决策人评分')),
                ('source_weight', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='来源权重')),
                ('source_list', models.JSONField(blank=True, default=list, verbose_name='多源命中')),
                ('valid_status', models.CharField(choices=[('unknown', '未知'), ('valid', '有效'), ('empty', '空号'), ('stopped', '停机')], default='unknown', max_length=16, verbose_name='号码状态')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('audit_log', models.JSONField(blank=True, default=list, verbose_name='审计日志')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_contacts', to=settings.AUTH_USER_MODEL, verbose_name='领取人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='biz.company')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'dim_contact',
                'ordering': ('-role_score', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tender', '招标'), ('financing', '融资'), ('recruit', '招聘'), ('lawsuit', '诉讼'), ('new_branch', '新设分支')], max_length=16, verbose_name='事件类型')),
                ('event_date', models.DateField(verbose_name='事件日期')),
                ('event_detail', models.JSONField(blank=True, default=dict, verbose_name='事件详情')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='来源URL')),
                ('source_platform', models.CharField(blank=True, default='', max_length=32, verbose_name='来源平台')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='biz.company')),
            ],
            options={
                'verbose_name': '企业事件',
                'verbose_name_plural': '企业事件',
                'db_table': 'fact_company_event',
                'ordering': ('-event_date',),
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city', 'industry_l3'], name='dim_company_city_452e93_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['insured_count', 'recruit_cnt_30d', 'tender_cnt_90d'], name='dim_company_insured_25a292_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['reg_date'], name='dim_company_reg_dat_3f43a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company'], name='dim_contact_company_dd0de4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['role_score'], name='dim_contact_role_sc_70cd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='companyevent',
            index=models.Index(fields=['company', 'event_date'], name='fact_compan_company_099b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='companyevent',
            index=models.Index(fields=['event_type', 'event_date'], name='fact_compan_event_t_2803c5_idx'),
        ),
    ]
