# Generated by Django 4.2.30 on 2026-07-31 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='推广昵称')),
                ('invite_code', models.CharField(max_length=32, unique=True, verbose_name='邀请码')),
                ('rate', models.DecimalField(decimal_places=2, default='0.20', max_digits=4, verbose_name='返佣比例')),
                ('customers', models.IntegerField(default=0, verbose_name='推广人数')),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '已冻结')], default='active', max_length=16, verbose_name='状态')),
                ('freeze_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='冻结原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '推广员',
                'verbose_name_plural': '推广员',
                'db_table': 'dist_promoter',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_id', models.CharField(max_length=64, unique=True, verbose_name='提现编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('channel', models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝')], default='wechat', max_length=16, verbose_name='收款渠道')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已打款'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='distribution.promoter', verbose_name='推广员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'db_table': 'dist_withdrawal',
            },
        ),
        migrations.CreateModel(
            name='PromoPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='客户大数据平台', max_length=128, verbose_name='海报标题')),
                ('image_url', models.CharField(blank=True, default='', max_length=512, verbose_name='海报图片 URL')),
                ('trial_price', models.DecimalField(decimal_places=2, default='0.01', max_digits=6, verbose_name='体验包价格')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='distribution.promoter')),
            ],
            options={
                'verbose_name': '推广海报',
                'verbose_name_plural': '推广海报',
                'db_table': 'dist_poster',
            },
        ),
        migrations.CreateModel(
            name='DistributionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('plan_code', models.CharField(default='trial', max_length=32, verbose_name='套餐编码')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('channel', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝')], default='wechat', max_length=16, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunded', '已退款'), ('closed', '已关闭')], default='pending', max_length=16, verbose_name='状态')),
                ('commission_amount', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='佣金金额')),
                ('commission_status', models.CharField(choices=[('pending', '待结算'), ('paid', '已结算'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='佣金状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='distribution.promoter', verbose_name='推广员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '分销订单',
                'verbose_name_plural': '分销订单',
                'db_table': 'dist_order',
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_subject', models.CharField(blank=True, default='', max_length=64, verbose_name='实名主体')),
                ('plan_status', models.CharField(blank=True, default='', max_length=32, verbose_name='套餐')),
                ('customer_contact', models.CharField(blank=True, default='', max_length=64, verbose_name='联系方式')),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='设备 IP')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('payment_channel', models.CharField(blank=True, default='', max_length=16, verbose_name='支付渠道')),
                ('payment_history', models.IntegerField(default=0, verbose_name='支付次数')),
                ('commission_history', models.IntegerField(default=0, verbose_name='佣金笔数')),
                ('operation_logs', models.IntegerField(default=0, verbose_name='操作次数')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reports', to='distribution.promoter', verbose_name='推广员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reports', to=settings.AUTH_USER_MODEL, verbose_name='客户用户')),
            ],
            options={
                'verbose_name': '客户登记报表',
                'verbose_name_plural': '客户登记报表',
                'db_table': 'dist_customer_report',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='佣金金额')),
                ('rate', models.DecimalField(decimal_places=2, default='0.20', max_digits=4, verbose_name='返佣比例')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('paid', '已结算'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='distribution.distributionorder', verbose_name='来源订单')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='distribution.promoter', verbose_name='推广员')),
            ],
            options={
                'verbose_name': '佣金记录',
                'verbose_name_plural': '佣金记录',
                'db_table': 'dist_commission',
                'ordering': ('-created_at',),
            },
        ),
    ]
