# Generated by Django 4.2.30 on 2026-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='佣金金额'),
        ),
        migrations.AlterField(
            model_name='distributionorder',
            name='commission_amount',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=12, verbose_name='佣金金额'),
        ),
    ]
