# Generated by Django 4.2.30 on 2026-07-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='withdrawn_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='累计已提现'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='分账流水号'),
        ),
        migrations.AlterField(
            model_name='customerreport',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='注册 IP'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='提现单号'),
        ),
    ]
