# Generated by Django 4.2.30 on 2026-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_promoter_withdrawn_total_withdrawal_payout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='withdrawn_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计已提现'),
        ),
    ]
