# Generated by Django 4.2.30 on 2026-08-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=64, unique=True, verbose_name='券码')),
                ('coupon_name', models.CharField(max_length=64, verbose_name='券名')),
                ('discount_type', models.CharField(choices=[('fixed', '立减'), ('percent', '折扣')], default='fixed', max_length=16, verbose_name='类型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='门槛')),
                ('cond_first_purchase', models.BooleanField(default=False, verbose_name='仅首充')),
                ('cond_from_plan', models.CharField(blank=True, default='', max_length=32, verbose_name='从套餐')),
                ('cond_to_plan', models.CharField(blank=True, default='', max_length=32, verbose_name='升到套餐')),
                ('expiry_days', models.IntegerField(default=30, verbose_name='有效期(天)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='PlanDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=32, unique=True, verbose_name='套餐编码')),
                ('plan_name', models.CharField(max_length=64, verbose_name='套餐名')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月价')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='年价')),
                ('concurrent_tasks', models.IntegerField(default=1, verbose_name='并发任务数')),
                ('daily_leads', models.IntegerField(default=30, verbose_name='每日线索上限')),
                ('crawl_min_interval_min', models.IntegerField(default=15, verbose_name='采集最小间隔(分)')),
                ('crawling_speed', models.CharField(default='slow', max_length=16, verbose_name='爬虫速度')),
                ('daily_ai_summary', models.IntegerField(default=10, verbose_name='每日AI摘要')),
                ('daily_ai_copy', models.IntegerField(default=5, verbose_name='每日AI话术')),
                ('ai_monthly_total', models.IntegerField(default=0, verbose_name='月度AI总额')),
                ('export_single_limit', models.IntegerField(default=50, verbose_name='单次导出上限')),
                ('export_async', models.BooleanField(default=False, verbose_name='异步导出')),
                ('keyword_total_limit', models.IntegerField(default=20, verbose_name='关键词总上限')),
                ('keyword_per_task', models.IntegerField(default=10, verbose_name='单任务词上限')),
                ('monitoring_tasks', models.IntegerField(default=0, verbose_name='监控任务数(-1不限)')),
                ('industry_templates', models.IntegerField(default=0, verbose_name='行业模板数(-1全部)')),
                ('alert_channels', models.CharField(blank=True, default='', max_length=64, verbose_name='告警渠道')),
                ('heatmap_level', models.CharField(default='none', max_length=16, verbose_name='热力图')),
                ('sub_accounts', models.IntegerField(default=0, verbose_name='子账号数(-1不限)')),
                ('lead_locking', models.BooleanField(default=False, verbose_name='线索锁定')),
                ('lead_retention_days', models.IntegerField(default=7, verbose_name='线索保留天数')),
                ('lead_masking', models.CharField(default='light', max_length=16, verbose_name='脱敏级别')),
                ('regional_filter', models.BooleanField(default=False, verbose_name='区县地域过滤')),
                ('data_reports', models.BooleanField(default=False, verbose_name='经营数据报表')),
                ('operation_service', models.BooleanField(default=False, verbose_name='人工运营服务')),
                ('permission_levels', models.BooleanField(default=False, verbose_name='权限分级')),
                ('private_deployment', models.BooleanField(default=False, verbose_name='私有化部署')),
                ('yearly_bonus', models.JSONField(blank=True, default=dict, verbose_name='年付福利')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '套餐定义',
                'verbose_name_plural': '套餐定义',
                'db_table': 'plan_definition',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_date', models.DateField(verbose_name='额度日期')),
                ('leads_used', models.IntegerField(default=0, verbose_name='已用线索')),
                ('leads_limit', models.IntegerField(default=30, verbose_name='线索上限')),
                ('ai_summary_used', models.IntegerField(default=0, verbose_name='已用摘要')),
                ('ai_summary_limit', models.IntegerField(default=10, verbose_name='摘要上限')),
                ('ai_copy_used', models.IntegerField(default=0, verbose_name='已用话术')),
                ('ai_copy_limit', models.IntegerField(default=5, verbose_name='话术上限')),
                ('export_used', models.IntegerField(default=0, verbose_name='已导出')),
                ('export_limit', models.IntegerField(default=50, verbose_name='导出上限')),
                ('is_demoted', models.BooleanField(default=False, verbose_name='静默降权')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户额度',
                'verbose_name_plural': '用户额度',
                'db_table': 'user_quota',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=16, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='commerce.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupon',
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', '新建任务'), ('delete_task', '删除任务'), ('toggle_task', '启停任务'), ('export', '导出'), ('purchase', '购买'), ('realname', '实名')], max_length=32, verbose_name='动作')),
                ('action_detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip', models.CharField(blank=True, default='', max_length=45, verbose_name='IP')),
                ('is_violation', models.BooleanField(default=False, verbose_name='是否违规')),
                ('penalty', models.CharField(blank=True, default='', max_length=255, verbose_name='处罚')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '行为日志',
                'verbose_name_plural': '行为日志',
                'db_table': 'user_behavior_log',
            },
        ),
        migrations.CreateModel(
            name='ServicePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=64, verbose_name='服务编码')),
                ('service_name', models.CharField(max_length=64, verbose_name='服务名')),
                ('service_type', models.CharField(choices=[('monthly', '月度订阅'), ('one_time', '一次性'), ('enterprise', '企业专属')], max_length=16, verbose_name='类型')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('bonus_value', models.IntegerField(default=0, verbose_name='赠量(条/天)')),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=16, verbose_name='状态')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开始')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='到期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '增值服务',
                'verbose_name_plural': '增值服务',
                'db_table': 'service_purchase',
            },
        ),
        migrations.CreateModel(
            name='RealNameAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_md5', models.CharField(max_length=32, unique=True, verbose_name='身份证MD5(一证一号)')),
                ('real_name', models.CharField(max_length=64, verbose_name='真实姓名')),
                ('id_card_tail', models.CharField(blank=True, default='', max_length=4, verbose_name='身份证后4位')),
                ('face_image_path', models.CharField(blank=True, default='', max_length=255, verbose_name='人脸照片')),
                ('face_verified', models.BooleanField(default=False, verbose_name='人脸核验通过')),
                ('verify_provider', models.CharField(blank=True, default='', max_length=32, verbose_name='核验服务商')),
                ('license_image_path', models.CharField(blank=True, default='', max_length=255, verbose_name='营业执照')),
                ('license_verified', models.BooleanField(default=False, verbose_name='执照核验')),
                ('auth_status', models.CharField(choices=[('pending', '待核验'), ('verified', '已认证'), ('rejected', '已驳回'), ('banned', '已处罚')], default='pending', max_length=16, verbose_name='认证状态')),
                ('ban_until', models.DateTimeField(blank=True, null=True, verbose_name='禁实名至')),
                ('ban_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='处罚原因')),
                ('auth_date', models.DateTimeField(blank=True, null=True, verbose_name='认证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realname', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '实名认证',
                'verbose_name_plural': '实名认证',
                'db_table': 'real_name_auth',
            },
        ),
        migrations.CreateModel(
            name='DeviceIpControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='IP')),
                ('device_id', models.CharField(max_length=128, verbose_name='设备ID')),
                ('register_count', models.IntegerField(default=0, verbose_name='该IP注册数')),
                ('action', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('collect', '采集')], default='register', max_length=16, verbose_name='动作')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='拦截')),
                ('block_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='拦截原因')),
                ('frozen_until', models.DateTimeField(blank=True, null=True, verbose_name='冻结至')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '设备IP管控',
                'verbose_name_plural': '设备IP管控',
                'db_table': 'device_ip_control',
            },
        ),
        migrations.AddConstraint(
            model_name='userquota',
            constraint=models.UniqueConstraint(fields=('user', 'quota_date'), name='uk_user_quota_date'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='uk_user_coupon'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['user', 'created_at'], name='user_behavi_user_id_a3cbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorlog',
            index=models.Index(fields=['is_violation'], name='user_behavi_is_viol_dac2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepurchase',
            index=models.Index(fields=['user', 'status'], name='service_pur_user_id_6b3505_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepurchase',
            index=models.Index(fields=['expiry_date'], name='service_pur_expiry__b52112_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceipcontrol',
            index=models.Index(fields=['ip_address'], name='device_ip_c_ip_addr_8ace3b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceipcontrol',
            index=models.Index(fields=['device_id'], name='device_ip_c_device__91058f_idx'),
        ),
    ]
