# Generated by Django 4.2.30 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='任务名')),
                ('keywords', models.TextField(verbose_name='关键词（逗号分隔）')),
                ('platforms', models.JSONField(default=list, verbose_name='目标平台')),
                ('pages', models.IntegerField(default=1, verbose_name='采集页数')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('total', models.IntegerField(default=0, verbose_name='总量')),
                ('processed', models.IntegerField(default=0, verbose_name='已处理')),
                ('found', models.IntegerField(default=0, verbose_name='发现线索')),
                ('message', models.TextField(blank=True, default='', verbose_name='消息')),
                ('schedule_type', models.CharField(blank=True, default='', max_length=16, verbose_name='调度类型')),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=64, verbose_name='Cron 表达式')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次运行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
                'db_table': 'crawl_task',
                'ordering': ('-id',),
            },
        ),
    ]
