# Generated by Django 4.2.30 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', max_length=32, verbose_name='任务ID')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('xiaohongshu', '小红书'), ('kuaishou', '快手'), ('weibo', '微博'), ('zhihu', '知乎'), ('tieba', '贴吧')], max_length=24, verbose_name='平台')),
                ('item_id', models.CharField(blank=True, default='', max_length=64, verbose_name='平台内容ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='作者')),
                ('author_id', models.CharField(blank=True, default='', max_length=64, verbose_name='作者ID')),
                ('url', models.URLField(blank=True, default='', verbose_name='原文链接')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论')),
                ('share_count', models.IntegerField(default=0, verbose_name='转发')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('region', models.CharField(blank=True, default='', max_length=50, verbose_name='地域标签')),
                ('demand', models.CharField(blank=True, default='', max_length=50, verbose_name='需求标签')),
                ('intent_label', models.CharField(choices=[('high', '高意向'), ('medium', '中意向'), ('low', '低意向'), ('none', '无意向')], default='none', max_length=16, verbose_name='意向标签')),
                ('intent_score', models.IntegerField(default=0, verbose_name='意向分')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, verbose_name='打分明细')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('location_text', models.CharField(blank=True, default='', max_length=200, verbose_name='地点文本')),
                ('status', models.CharField(default='new', max_length=16, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='拉黑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '线索',
                'verbose_name_plural': '线索',
                'db_table': 'lead',
                'ordering': ('-intent_score', '-id'),
            },
        ),
    ]
