# Generated by Django 4.2.30 on 2026-07-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'platform'], name='lead_user_id_af3382_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'intent_score'], name='lead_user_id_b43d50_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'region'], name='lead_user_id_5f5415_idx'),
        ),
    ]
