# Generated by Django 4.2.30 on 2026-08-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('shipinhao', '视频号'), ('kuaishou', '快手')], max_length=16, verbose_name='平台')),
                ('account_name', models.CharField(max_length=64, verbose_name='账号名')),
                ('cookie_encrypted', models.TextField(blank=True, default='', verbose_name='Cookie密文')),
                ('status', models.CharField(choices=[('active', '可用'), ('frozen', '冻结'), ('cooling', '冷却')], default='active', max_length=16, verbose_name='状态')),
                ('health_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='健康度')),
                ('today_sent', models.IntegerField(default=0, verbose_name='今日已发')),
                ('hourly_sent', models.IntegerField(default=0, verbose_name='本时已发')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最后发送')),
                ('last_error', models.CharField(blank=True, default='', max_length=200, verbose_name='最后错误')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账号池',
                'verbose_name_plural': '账号池',
                'db_table': 'account_pool',
                'ordering': ('-health_score',),
            },
        ),
        migrations.CreateModel(
            name='DmTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模板名')),
                ('round', models.IntegerField(default=1, verbose_name='轮次')),
                ('content', models.TextField(verbose_name='话术内容')),
                ('media_type', models.CharField(choices=[('text', '文本'), ('card', '名片'), ('qrcode', '二维码')], default='text', max_length=16, verbose_name='素材类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '话术模板',
                'verbose_name_plural': '话术模板',
                'db_table': 'dm_template',
            },
        ),
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('video', '视频'), ('live_room', '直播间'), ('competitor_account', '竞品账号')], max_length=32, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='平台侧ID')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('shipinhao', '视频号'), ('kuaishou', '快手')], max_length=16, verbose_name='平台')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('monitor_status', models.CharField(choices=[('active', '监控中'), ('paused', '已暂停'), ('stopped', '已停止')], default='active', max_length=16, verbose_name='监控状态')),
                ('last_pull_time', models.DateTimeField(blank=True, null=True, verbose_name='上次拉取')),
                ('pull_interval_min', models.IntegerField(default=5, verbose_name='拉取间隔(分)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'db_table': 'monitor_target',
            },
        ),
        migrations.CreateModel(
            name='TriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规则名')),
                ('cond_intent_min', models.DecimalField(decimal_places=2, default=0.7, max_digits=4, verbose_name='意图分阈值')),
                ('cond_fan_min', models.IntegerField(default=50, verbose_name='粉丝下限')),
                ('cond_fan_max', models.IntegerField(default=5000, verbose_name='粉丝上限')),
                ('cond_exclude_following', models.BooleanField(default=True, verbose_name='排除互关')),
                ('action_type', models.CharField(choices=[('send_dm', '发私信'), ('reply_comment', '回评'), ('push_card', '推名片')], max_length=16, verbose_name='动作类型')),
                ('round', models.IntegerField(default=1, verbose_name='触达轮次')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='monitor.dmtemplate')),
            ],
            options={
                'verbose_name': '触发规则',
                'verbose_name_plural': '触发规则',
                'db_table': 'trigger_rule',
            },
        ),
        migrations.CreateModel(
            name='RawComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=64, verbose_name='平台评论ID')),
                ('platform', models.CharField(choices=[('douyin', '抖音'), ('shipinhao', '视频号'), ('kuaishou', '快手')], max_length=16, verbose_name='平台')),
                ('uid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='头像')),
                ('fan_cnt', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('region', models.CharField(blank=True, default='', max_length=32, verbose_name='地区')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复数')),
                ('parent_comment_id', models.CharField(blank=True, default='', max_length=64, verbose_name='父评论ID')),
                ('comment_time', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('pulled_at', models.DateTimeField(auto_now_add=True, verbose_name='拉取时间')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='monitor.monitortarget')),
            ],
            options={
                'verbose_name': '原始评论',
                'verbose_name_plural': '原始评论',
                'db_table': 'raw_comment',
                'ordering': ('-pulled_at',),
            },
        ),
        migrations.CreateModel(
            name='IntentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='意图分')),
                ('hit_keyword', models.CharField(blank=True, default='', max_length=64, verbose_name='命中词')),
                ('level', models.CharField(choices=[('kw_only', '关键词命中'), ('nlp_pass', 'NLP通过'), ('llm_pass', 'LLM通过')], default='kw_only', max_length=16, verbose_name='识别级别')),
                ('is_ad', models.BooleanField(default=False, verbose_name='广告/同行/已转化')),
                ('is_converted', models.BooleanField(default=False, verbose_name='已转化')),
                ('llm_raw', models.JSONField(blank=True, default=dict, verbose_name='LLM原始结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('raw_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent', to='monitor.rawcomment')),
            ],
            options={
                'verbose_name': '意图评论',
                'verbose_name_plural': '意图评论',
                'db_table': 'intent_comment',
                'ordering': ('-intent_score',),
            },
        ),
        migrations.AddIndex(
            model_name='rawcomment',
            index=models.Index(fields=['target'], name='raw_comment_target__28642b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcomment',
            index=models.Index(fields=['uid'], name='raw_comment_uid_a4c7e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawcomment',
            constraint=models.UniqueConstraint(fields=('platform', 'comment_id'), name='uk_raw_comment'),
        ),
        migrations.AddConstraint(
            model_name='monitortarget',
            constraint=models.UniqueConstraint(fields=('platform', 'target_type', 'target_id'), name='uk_monitor_target'),
        ),
        migrations.AddIndex(
            model_name='intentcomment',
            index=models.Index(fields=['intent_score'], name='intent_comm_intent__5ff89e_idx'),
        ),
        migrations.AddIndex(
            model_name='intentcomment',
            index=models.Index(fields=['is_converted'], name='intent_comm_is_conv_4a894a_idx'),
        ),
    ]
